### ISSUE TITLE
Delete Course from Cart

### ISSUE THREAD

**Issue by ToddSpainhour** [nss-evening-cohort-11/TeamLearningConcepts#40]
## User Story
As a user, I want to be able to remove courses from my cart.

## AC
***Given*** that a customer has an item in their cart

***When*** they click the *Delete* button

***Then*** the product is removed from their cart

###### Delete Single Course from Cart
- [x] create an `X` button on the course cards
- [x] use an `OnClick` to call a function that calls the delete function in the data file
  - this function will live in the `ShoppingCart` component and be passed down and called in the `CartCourseCards` file, where the button lives
  - it should take in the `courseId` and then it should declare the `invoiceId` variable from the state
  - then pass both of those into the function call for the `axios` call living in the `InvoiceLineItemData` file
- [x] this delete function should only be deleting a single `InvoiceLineItem`

###### Remove all Courses from Cart (Cancel button)
- [x] create a button on the shopping cart page
- [x] use an `OnClick` to call a function that calls the delete function in the data file
- [x] in the data file, create a delete function that will delete the `Invoice` row and the `InvoiceLineItems` associated with that `InvoiceId`

###### Delete Single Course from Cart
- [x] create a method in the `InvoiceLineItemRepository` to delete a single line item from the `InvoiceLineItem` table in the database
  - this method will take in an `InvoiceId` and a `CourseId` that is passed in from the controller
  - the `InvoiceId` and `CourseId` values will be parameters for the sql string to query the database
- [x] create a corresponding method in the `InvoiceLineItemController`
  - this method takes in the `InvoiceId` and `CourseId` being passed back from the front end data call
  - then it calls the repository method passes back those values to that method

###### Remove all Courses from Cart (Cancel button)
- [x] create a method in the `InvoiceRepository` to delete the `Invoice` and all `InvoiceLineItem`s associated with the `InvoiceId` being deleted
  - this takes in the `InvoiceId`
- [x] query:
```
Delete Invoice, InvoiceLineItem
from Invoice
inner join InvoiceLineItem
on InvoiceLineItem.InvoiceId = Invoice.InvoiceId
Where Invoice.InvoiceId = @InvoiceId
```
- [x] create a corresponding method in the `InvoiceController`
  - this should take in the `InvoiceId` and pass it back to the method in the repository to then passed into the query.

**Comment by wickedanna** [comment]
The SQL query written above doesn't work, because very simply, you can't use a join on a delete. The solution we came up with was very simple. We used two queries in the same call to the database to delete the `InvoiceLineItem` rows associated with the `InvoiceId` and then deleted the `Invoice` row with that id. Like this:
```
Delete from Invoice
Where InvoiceId = @invoice

Delete from InvoiceLineItem
Where InvoiceId = @invoice
```
